### ISSUE TITLE
Bug interacting with Templater

### ISSUE THREAD

**Issue by menagerie198** [Vinzent03/obsidian-hotkeys-for-templates#14]
OS: Windows 10
Hotkeys for Templates 1.4.2 -- Templater version: >1.8.1
Obsidian version: 0.12.16
Templater ... ## <% tp.date.now("HHmm") %> – 

**Describe the bug**
I have the above Template attached to a hotkey (using the 'Hotkeys for Templates' plugin - Alt+T). It has stopped working in the last 24 hours (>v1.8.1 of Templater). 

**Expected behaviour**
Alt+T calls and renders an H2 with the current time.

**Additional context**
I initially posted a bug report on the Templater git - they got back to me with the following (apologies for this, as I don’t really understand what they are actually saying here)...

"I believe you will find a `this.templaterPlugin.templater.append_template` is not a function error in the console.

I think this error comes from the `append_template` having changed name during a refactor. This should probably be filed as a bug with `Hotkeys For Templates` plugin, not `Templater` itself."

**Comment by Vinzent03** [comment]
Fixed in [1.4.3](https://github.com/Vinzent03/obsidian-hotkeys-for-templates/releases/tag/1.4.3)
